# Generated by Django 4.0.4 on 2022-04-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_alter_profile_posted_news_alter_profile_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='posted_news',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
