# Generated by Django 4.0.4 on 2022-04-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_picture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='picture',
            field=models.ManyToManyField(to='blog.picture'),
        ),
    ]
