# Generated by Django 4.0.4 on 2022-04-18 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_name_blogpost_title_remove_blogpost_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='news',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost'),
            preserve_default=False,
        ),
    ]
