# Generated by Django 4.0.4 on 2022-04-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_picture_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='created_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
