# Generated by Django 4.0.4 on 2022-04-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_picture_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='created_at',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='created_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
