alphabet = 'abcdefg'
print('Ex.1', alphabet[:])
print('Ex.2', alphabet[:: -1])
print('Ex.3', alphabet[:: 2])
print('Ex.4', alphabet[1:: 2])
print('EX.5', alphabet[: 1])
print('EX.6', alphabet[: 5: -1])
print('Ex.7', alphabet[3:4])
print('Ex.8', alphabet[4:])
print('Ex.9', alphabet[3:5])
print('Ex.10', alphabet[4:2: -1])