# Generated by Django 4.0.5 on 2022-06-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Markets',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('count', models.PositiveSmallIntegerField()),
                ('price', models.PositiveBigIntegerField()),
                ('market', models.ManyToManyField(related_name='market', to='shops.marketmodel')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
