# Generated by Django 4.0.4 on 2022-04-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'published')], default='d', max_length=2),
        ),
    ]
