# Generated by Django 4.0.4 on 2022-04-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_tags_comment_news_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tag',
        ),
        migrations.AddField(
            model_name='tags',
            name='news',
            field=models.ManyToManyField(to='news.news'),
        ),
    ]
