# Generated by Django 4.0.4 on 2022-04-16 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='news',
        ),
        migrations.AddField(
            model_name='tags',
            name='news',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='news.news'),
            preserve_default=False,
        ),
    ]
