# Generated by Django 4.0.3 on 2022-04-05 14:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvCreator',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=200)),
                ('author_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
            options={
                'verbose_name': 'author',
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='AdvType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100, unique=True, verbose_name='Type name')),
                ('type_slug', models.SlugField(verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Adv',
            fields=[
                ('adv_id', models.AutoField(primary_key=True, serialize=False)),
                ('adv_name', models.CharField(max_length=300, unique=True, verbose_name='Name')),
                ('adv_slug', models.SlugField(unique=True, verbose_name='slug')),
                ('adv_context', models.TextField(verbose_name='Context')),
                ('adv_price', models.FloatField(verbose_name='Price')),
                ('adv_created_on', models.DateTimeField(auto_now_add=True)),
                ('adv_updates_on', models.DateTimeField(auto_now=True)),
                ('adv_ends_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ends on ->')),
                ('adv_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_author', to='advertisements_app.advcreator', verbose_name='Author Name')),
                ('adv_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foreign_type', to='advertisements_app.advtype', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'advertisement',
                'db_table': 'advertisement',
            },
        ),
    ]
