# Generated by Django 4.0.5 on 2022-06-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_remove_profile_name_alter_profile_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
    ]
