# Generated by Django 4.0.3 on 2022-04-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['created_at'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
